- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.gitconfig: gitconfig
    ~/.zshrc: zshrc
    ~/.tmux.conf: tmux.conf
    ~/.tmux-spotify-info: .tmux-spotify-info/tmux-spotify-info
    ~/.tmux/plugins/tpm: .tpm/


- shell:
    - [git submodule update --init --recursive, Installing submodules]